// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkMbJNkuZ809j4KcxDqKssJe2jZo2LaJ4',
    appId: '1:663301863031:web:cffd017b82bd49a8f9b872',
    messagingSenderId: '663301863031',
    projectId: 'campus-recruitment-6c552',
    authDomain: 'campus-recruitment-6c552.firebaseapp.com',
    storageBucket: 'campus-recruitment-6c552.appspot.com',
    measurementId: 'G-CXR3SB2800',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARPobpPaZC0Iabsl18-CoYkowmSRKAsrU',
    appId: '1:663301863031:android:df11a09a07eb5a6ff9b872',
    messagingSenderId: '663301863031',
    projectId: 'campus-recruitment-6c552',
    storageBucket: 'campus-recruitment-6c552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuVRFAzy7mpcsPPmm-u0vEbgMHQM2ytEo',
    appId: '1:663301863031:ios:d926353af1e6f0b4f9b872',
    messagingSenderId: '663301863031',
    projectId: 'campus-recruitment-6c552',
    storageBucket: 'campus-recruitment-6c552.appspot.com',
    iosBundleId: 'com.example.campusRecruitment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuVRFAzy7mpcsPPmm-u0vEbgMHQM2ytEo',
    appId: '1:663301863031:ios:985b317e8f80e2dbf9b872',
    messagingSenderId: '663301863031',
    projectId: 'campus-recruitment-6c552',
    storageBucket: 'campus-recruitment-6c552.appspot.com',
    iosBundleId: 'com.example.campusRecruitment.RunnerTests',
  );
}
